### ISSUE TITLE
Create Landing page front-end

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/zenska-vizija-nextjs-firebase#8]
To complete this you need to create landing page according to the design in figma:

- [x] create landing page 
- [x] create responsive design

**Comment by DenisKantic** [comment]
Good work for now. Still remains responsive design, but we will get to it.

**Comment by laststonedjs** [comment]
Thanks mate, let's go even stronger and better!

**Comment by DenisKantic** [comment]
Done!
